MODEL:
    NUM_CLASSES: 11
    BACKBONE:
        NAME: 'improved'
        PRETRAINED: False
        OUT_CHANNELS: [64, 128, 256, 128, 128, 64, 64]
        INPUT_CHANNELS: 3
    PRIORS:
        FEATURE_MAPS: [[76, 76], [38, 38], [19, 19], [10, 10], [5, 5], [3, 3], [1, 1]]
        STRIDES: [[4, 4], [8, 8], [16, 16], [32, 32], [64, 64], [100, 100], [300, 300]]
        MIN_SIZES: [[15, 15], [30, 30], [60, 60], [111, 111], [162, 162], [213, 213], [264, 264]]
        MAX_SIZES: [[30, 30], [60, 60], [111, 111], [162, 162], [213, 213], [264, 264], [315, 315]]
        ASPECT_RATIOS: [[2], [2], [2, 3], [2, 3], [2, 3], [2], [2]]
        BOXES_PER_LOCATION: [4, 4, 6, 6, 6, 4, 4]
INPUT:
    IMAGE_SIZE: [300, 300]
DATASETS:
    TRAIN: ("mnist_detection_train", "mnist_detection_val")
    TEST: ("mnist_detection_val", )
SOLVER:
    MAX_ITER: 14000
    GAMMA: 0.01
    BATCH_SIZE: 16
    LR: 5e-4
OUTPUT_DIR: 'outputs/improved'
DATASET_DIR: "datasets"